Добавил наставника /readme.md
htmlacademy-htmlcss/98669-device-29 pull request #1
Opened 2020-09-08 11:27 UTC by Ranyar

2020-09-08 13:27 UTC, ILoyso requested changes

2020-09-08 13:27 UTC, ILoyso commented on Readme.md
> +* Наставник: `[Ирина Шашева](https://htmlacademy.ru/profile/loyso)`.
Имя наставника нужно сделать ссылкой, по аналогии с именем студента
Вывод из файле Readme.md можно увидеть на странице репозитория, после файлов проекта
![image](https://user-images.githubusercontent.com/18247717/92482275-1bdaf180-f1f0-11ea-8d5a-57ae7471826c.png)

2020-09-09 11:24 UTC, Ranyar commented on Readme.md
> +* Наставник: `[Ирина Шашева](https://htmlacademy.ru/profile/loyso)`.
![2020-09-09_16-23-22](https://user-images.githubusercontent.com/14089426/92592338-d9c9b280-f2b8-11ea-8e02-c7ed89c000f4.png)
Поправил, сделал ссылкой)

2020-09-09 12:39 UTC, ILoyso requested changes

2020-09-09 12:39 UTC, ILoyso commented on Readme.md
> +* Наставник: <a href="https://htmlacademy.ru/profile/loyso" rel="nofollow">Ирина Шашева.</a>
Это рабочий вариант, но он не очень хорошо подходит сюда. Тег `<a>` - это html-тег, а здесь у нас маркдаун синтаксис. Посмотри внимательно, как оформлены остальные ссылки в этом файле, для этого используются квадратные и круглые скобки. Твой первый вариант был практически идеальным, в нем только были лишние кавычки (` - такие)

2020-09-09 13:34 UTC, Ranyar commented on Readme.md
> +* Наставник: <a href="https://htmlacademy.ru/profile/loyso" rel="nofollow">Ирина Шашева.</a>
Так и подумал, кавычки ввели меня в заблуждение)
Поправил.

2020-09-09 14:28 UTC, ILoyso commented on Readme.md
> +* Наставник: <a href="https://htmlacademy.ru/profile/loyso" rel="nofollow">Ирина Шашева.</a>
Отлично! И нажимай на гитхабе пожалуйста "Resolve conversation", если комментарий обработан и исправлен тобой :)

2020-09-09 14:28 UTC, ILoyso approved these changes

2020-09-09 14:28 UTC, merged