Декоративные элементы и pixel-perfect для главной страницы
htmlacademy-htmlcss/98669-device-29 pull request #10
Opened 2020-10-25 08:13 UTC by Ranyar

2020-10-25 10:50 UTC, ILoyso commented on index.html
> +          </div>
Избыточный див, этот паддинг делается всей секции

2020-10-25 10:50 UTC, ILoyso commented on index.html
> +          <div class="footer-brick"></div>
Если целишь на дополнительные критерии, то это избыточный тег и по Д2 не пройдет. Такие вещи делаются исключительно декором через css

2020-10-25 10:50 UTC, ILoyso commented on index.html
> +                <p class="visually-hidden">Facebook</p>
span уместнее

2020-10-25 10:50 UTC, ILoyso commented on index.html
> +    <section class="modal modal-writeus">
Здесь и ниже выравнивание кода поехало, плюс нет закрывающего тега секции

2020-10-25 10:50 UTC, ILoyso commented on css/style.css
> +  margin-top: 44px;
У тебя сейчас везде марджины и верхние и нижние. Не исправляй уж, на на будущее, лучше старайся использовать подход, когда марджины однотипные - либо только верхние либо только нижние. Только так это можно комфортно поддерживать и поведение будет ожидаемым

2020-10-25 10:50 UTC, ILoyso commented on css/style.css
> +}
Любое переполнение ломает такой подход
Если нужно поменять местами блоки - флексы в помощь

2020-10-25 10:50 UTC, ILoyso commented on css/style.css
> +    background: var(--yellow-light);
Выравнивание кода

2020-10-25 10:50 UTC, ILoyso commented on css/style.css
> +.delivery {
http://joxi.ru/5mdgdaeh8vdPDr

2020-10-25 10:50 UTC, ILoyso commented on css/style.css
> +}
http://joxi.ru/12MzW3vTk4W6nA
Паддинги это внутренние отступы секции :(

2020-10-25 10:50 UTC, ILoyso commented on css/style.css
> +.logistics-list-item{
Пробел перед фигурной скобкой

2020-10-25 12:20 UTC, ILoyso requested changes
- очень много где поломалось выравнивание кода, нужно везде исправить
- есть ошибки валидатора
- добавил js, но он не работает. проверять его буду в рамках лекции по js, не нужно бежать вперед паровоза
- отдельно нужно проверить модалки, они сейчас обе визуально кривые, комментировать там построчно сложно, поэтому просто приведи их к виду как в макете

По пиксель перфекту
http://joxi.ru/l2Z4XgpC78YY4r
http://joxi.ru/DmB8lMvC4NppVA - первая кнопка должна быть активной сразу. Прям добавляешь её класс активный, сразу черная, без предварительных фокусов и тд. Нам нужно показать, что именно первый слайд сейчас выбран у пользователя
http://joxi.ru/823d9RVH86pYwA
http://joxi.ru/8AnEx7jCyqE4R2
http://joxi.ru/MAjE3xjCkvBDN2

2020-10-25 12:20 UTC, ILoyso commented on css/style.css
> +  padding: 92px 100px 60px 100px;
Фиксированная высота модалкам не задается

2020-10-25 12:20 UTC, ILoyso commented on css/style.css
> +.modal-writeus form {
Перед каждым селектором обычно ты ставишь перенос строки, значит здесь и ниже тоже везде нужно поставить

2020-10-25 12:20 UTC, ILoyso commented on css/style.css
> +}
Нельзя все и везде стилизовать по nth-child, если в верстке что-то поменяют местами, все сломается и так не должно быть.
Есть форма, в ней три ребенка и кнопка. Задаем флекс, включаем перенос, первым двум полям (которые по 50% ширины) задаем отдельный класс и там прописываем ширину 50%.

2020-10-25 12:20 UTC, ILoyso commented on css/style.css
> +  font-weight: normal;
Здесь и везде, где есть - font-weight цифрами пишем

2020-10-25 12:20 UTC, ILoyso commented on css/style.css
> +  font-family: Open Sans;
font-family пишем полностью, плюс единообразно - либо везде в кавычках, либо везде без

2020-10-25 12:20 UTC, ILoyso commented on css/style.css
> +}
- минимальную высоту задаем
- цвет из переменной должен быть

2020-10-25 15:30 UTC, Ranyar commented on css/style.css
> +}
Сделал

2020-10-25 15:37 UTC, Ranyar commented on css/style.css
> +  font-family: Open Sans;
Исправил здесь и в других местах, спасибо

2020-10-25 15:44 UTC, Ranyar commented on css/style.css
> +  font-weight: normal;
Поправил

2020-10-25 15:55 UTC, Ranyar commented on css/style.css
> +.modal-writeus form {
Поправил форматирование кода здесь и в других местах

2020-10-25 16:06 UTC, Ranyar commented on css/style.css
> +.search::before {
Убрал тень, заменив иконку - импортировал из макета с другого листа.

2020-10-25 16:10 UTC, Ranyar commented on css/style.css
> +}
Убрал

2020-10-25 16:30 UTC, Ranyar commented on css/style.css
> +  padding: 92px 100px 60px 100px;
Поправил

2020-10-25 18:58 UTC, Ranyar commented on css/style.css
> +.logistics-list-item{
Поправил

2020-10-25 19:25 UTC, Ranyar commented on index.html
> +                <p class="visually-hidden">Facebook</p>
Переделал

2020-10-26 13:02 UTC, Ranyar commented on css/style.css
> +    background: var(--yellow-light);
Выровнял здесь и далее

2020-10-26 13:11 UTC, Ranyar commented on css/style.css
> +}
Заменил маргины на паддинги

2020-10-26 13:13 UTC, Ranyar commented on css/style.css
> +}
Заменил margin-left на left

2020-10-26 13:15 UTC, Ranyar commented on css/style.css
> +  left: 931px;
Сделал

2020-10-26 15:03 UTC, Ranyar commented on index.html
> +    <section class="modal modal-writeus">
Поправил

2020-10-26 15:41 UTC, Ranyar commented on css/style.css
> +.delivery {
Сделал

2020-10-26 16:09 UTC, Ranyar commented on css/style.css
> +}
Перенес нижнюю границу с формы на само поле ввода, дергаться перестало.

2020-10-26 19:27 UTC, Ranyar commented on css/style.css
> +  margin-left: 187px;
Поправил

2020-10-26 20:29 UTC, Ranyar commented on index.html
> +          </div>
Убрал див, сделал общий паддинг для всей секции

2020-10-26 20:44 UTC, Ranyar commented on index.html
> +          <div class="footer-brick"></div>
Сделал

2020-10-26 20:48 UTC, Ranyar commented on css/style.css
> +  margin-top: 44px;
Понял, принял)
Вообще, большую часть марджинов между большими блоками исправил на паддинги

2020-10-26 21:01 UTC, Ranyar commented on css/style.css
> +}
Спасибо, приму к сведению!
Однако, здесь поправил, чтоб было нормально)

2020-10-26 21:08 UTC, Ranyar commented on css/style.css
> +}
Исправил и вынес все в отдельный общий класс

2020-10-26 22:01 UTC, Ranyar commented on css/style.css
>  }
![2020-10-27_03-00-28](https://user-images.githubusercontent.com/14089426/97233314-968fb880-1800-11eb-8692-574d0b46c514.png)

![2020-10-27_02-56-21](https://user-images.githubusercontent.com/14089426/97233202-5b8d8500-1800-11eb-99c0-e3d17a75f904.png)

Есть более изящное решение, но там пиксель-перфект получается не такой хороший, как в закомментированном варианте. Как быть?

2020-10-26 22:02 UTC, Ranyar commented on css/style.css
>  }
![2020-10-27_03-02-06](https://user-images.githubusercontent.com/14089426/97233456-d0f95580-1800-11eb-9311-78c5243886f0.png)
А вот изначальный результат, он более пиксель-в-пиксель

2020-10-26 22:11 UTC, Ranyar commented on css/style.css
>  }
Вынес для иконок общее в отдельный класс

2020-10-27 07:56 UTC, ILoyso commented on css/style.css
>  }
>Как быть?

Не наркоманить с ПП до упора, в этом нет смысла и если от этого страдает код, значит оно нам не надо. По критерию проходит? Проходит. Все, прекрасно :) 
Ну и плюс, можно попробовать делать не один большой правый марджин, а каждому элементу и левый и правый где-нибудь в половину от текущего

2020-10-27 08:45 UTC, Ranyar commented on css/style.css
> +}
Не совсем понимаю. Задать 3 rows вместо 3 columns? Но ведь там у всех элементов разная ширина?

2020-10-27 09:00 UTC, ILoyso commented on css/style.css
> +}
Нет, именно разметку изменить, html
https://codepen.io/ILoyso/pen/XWKRJOV?editors=1100 - там было и стало

2020-10-27 09:57 UTC, Ranyar commented on css/style.css
>  }
Остановился на компромиссном варианте, где мало кода и ПП попадает в критерии

2020-10-27 12:20 UTC, Ranyar commented on css/style.css
> +}
Действительно, очень изящное решение получилось, спасибо что подсказала!
Получилось, что сразу несколько классов лишними стали.

2020-10-27 14:26 UTC, Ranyar commented on css/style.css
> +}
Сделал немного иначе, но, кажется, тоже неплохо.

2020-10-27 14:40 UTC, Ranyar commented on css/style.css
> +}
![2020-10-27_19-38-03](https://user-images.githubusercontent.com/14089426/97316799-f7b09e00-188b-11eb-9589-1a9a534da608.png)
2 класса убрал, один добавил - экономия налицо)

2020-10-27 15:19 UTC, Ranyar commented on css/style.css
> +}
Сделал через флекс+реверс-колумн

2020-10-27 17:12 UTC, ILoyso requested changes
Выравнивание кода (плюс удаляем все лишние комментарии из разметки)
http://joxi.ru/Vm6Z6nVCvxgylm
http://joxi.ru/p27aWXVSN0lQor
http://joxi.ru/MAjE3xjCkv6V82
http://joxi.ru/5mdgdaeh8vRxyr
http://joxi.ru/823d9RVH86NEPA
http://joxi.ru/BA059KVfpBGlVr
http://joxi.ru/v293LkVIpGVdqr
http://joxi.ru/gmvp85KC1x7yzA
http://joxi.ru/52ag5LVhkGL9Or

2020-10-27 17:12 UTC, ILoyso commented on css/style.css
>  }
Задаем всем 21 и не сходим с ума ради ПП, все более чем ок если просто везде одинаковый 21 оставить

2020-10-27 17:12 UTC, ILoyso commented on css/style.css
> +}
```
 content: "";
 position: absolute;
 background-repeat: no-repeat;
```
можно вынести общее

2020-10-27 17:12 UTC, ILoyso commented on css/style.css
> +}
Три раза одно и то же повторяем

2020-10-27 17:12 UTC, ILoyso commented on css/style.css
> +}
Аналогично, трижды повторяем

2020-10-27 17:12 UTC, ILoyso commented on css/style.css
> +}
отступ

2020-10-27 17:12 UTC, ILoyso commented on css/style.css
> +  height: 170px;
ширина и высота не нужны

2020-10-27 18:18 UTC, Ranyar commented on css/style.css
> +  height: 170px;
Убрал

2020-10-27 18:19 UTC, Ranyar commented on css/style.css
> +}
Пофиксил

2020-10-27 18:20 UTC, Ranyar commented on css/style.css
> +.modal {
Задал с запасом теперь)

2020-10-27 18:23 UTC, Ranyar commented on css/style.css
> +}
Задал и вынес в общий класс

2020-10-27 18:23 UTC, Ranyar commented on index.html
> +          <div class="footer-brick"></div>
Убрал. Ночью уже делал, поэтому пропустил

2020-10-27 18:25 UTC, Ranyar commented on index.html
> +        <div class="writeus-input-wrapper half-width">
Убрал. Он остался от экспериментов с модалкой.

2020-10-27 19:06 UTC, Ranyar commented on css/style.css
>  }
Сделал

2020-10-27 19:31 UTC, Ranyar commented on css/style.css
> +.site-navigation-item:first-child:hover .dropdown-menu {
Done

2020-10-27 19:37 UTC, Ranyar commented on css/style.css
> +  border: 7px solid var(--white);
Убрал

2020-10-27 20:10 UTC, Ranyar commented on css/style.css
> +.modal-map {
Убрал лишнее, выровнял карту по макету

2020-10-27 20:18 UTC, Ranyar commented on css/style.css
> +}
Вынес общие вещи в отдельный класс

2020-10-27 20:20 UTC, Ranyar commented on css/style.css
> +}
Объединил свойства в один класс

2020-10-27 20:22 UTC, Ranyar commented on css/style.css
> +}
Объединил в общий класс

2020-10-27 20:23 UTC, Ranyar commented on css/style.css
> +.search::before {
Пока не получается сделать. В инспекторе по отдельности работает, когда ставишь чекбокс на разные состояния, а вместе - нет.

2020-10-28 08:16 UTC, ILoyso commented on css/style.css
> +.search::before {
Фиксится одной строчкой - добавления z-index для псевдоэлемента

2020-10-28 14:10 UTC, Ranyar commented on css/style.css
> +.search::before {
Пофиксил, спасибо!

2020-10-28 14:17 UTC, ILoyso approved these changes

2020-10-28 14:17 UTC, ILoyso commented on css/style.css
> +  height: 558px;
В прошлом ревью было - модалкам не задается высота (актуально и для карты и для формы).
Если здесь это добавлено ради центровки, то проблема не в отсутствии высоты, ищи другие подходы к центровке

2020-10-28 14:17 UTC, merged