Декоративные элементы и пиксель-перфект для внутренней страницы
htmlacademy-htmlcss/98669-device-29 pull request #11
Opened 2020-10-31 08:43 UTC by Ranyar

2020-10-31 10:38 UTC, ILoyso requested changes

2020-10-31 10:38 UTC, ILoyso commented on css/style.css
>  }
http://joxi.ru/823d9RVH8JkNYA

2020-10-31 10:38 UTC, ILoyso commented on css/style.css
> +}
Вместо того, чтобы задавать каждому отдельному айтему здесь разный марджин, лучше у чекбоксов и радиокнопок последнему элементу нижний марджин не задавать. И соответственно вынести там марджины из лейбла, и задавать их для элементов списка (всех, кроме последнего). Тогда здесь марджины можно будет плюс-минус не переопределять точечно

2020-10-31 14:01 UTC, Ranyar commented on catalog.html
> +                  <div class="range-filter">
Сделал

2020-10-31 14:03 UTC, Ranyar commented on catalog.html
> +              <input class="button" type="submit" name="form-submit" value="Показать">
Заменил на button

2020-10-31 14:10 UTC, Ranyar commented on css/style.css
>  }
Поправил

2020-10-31 14:16 UTC, Ranyar commented on css/style.css
>  }
Сделал

2020-10-31 14:23 UTC, Ranyar commented on css/style.css
> +}
Сделал, но пришлось немного скорректировать левый паддинг у списка.

2020-10-31 14:35 UTC, Ranyar commented on css/style.css
>  }
Сделал. Так действительно смотрится логичнее. Спасибо!

2020-10-31 17:40 UTC, Ranyar commented on css/style.css
>  }
Сделал

2020-10-31 17:40 UTC, Ranyar commented on css/style.css
> +}
Сделал

2020-10-31 17:41 UTC, Ranyar commented on css/style.css
> +}
Сделал

2020-10-31 17:44 UTC, Ranyar commented on catalog.html
>                    </li>
Сделал

2020-10-31 18:21 UTC, Ranyar commented on css/style.css
>  }
Сделал

2020-10-31 19:25 UTC, Ranyar commented on css/style.css
> +}
Центра не дает, к сожалению, такого точного позиционирования. И она работает, только если задать обертке кнопок ширину/высоту. Позиционирует по центру, но слишком большое расхождение получается(
![2020-11-01_00-24-18](https://user-images.githubusercontent.com/14089426/97788178-c9f38e00-1bd8-11eb-8bd4-a36e57b577c0.png)

2020-10-31 19:50 UTC, Ranyar commented on css/style.css
> +}
Сделал, но центровка без left получается менее идеальная:
![2020-11-01_00-43-33](https://user-images.githubusercontent.com/14089426/97788529-6159e080-1bdb-11eb-9930-d627124396ac.png)

2020-10-31 20:29 UTC, Ranyar commented on css/style.css
> +}
Вынес нижние маргины у label чекбоксов и задал их всем элементам списка filter-list, кроме последнего. Чекбоксы не трогал, они не являются элементами списка, и не совсем понимаю, как  лейбелы чекбоксов связаны с legend их блока. Селектор .filter-item:nth-child(2) пока закомментировал - его теперь можно убрать (если вообще цель была именно в этом), но тогда расхождение в два пикселя по высоте:
![2020-11-01_01-25-25](https://user-images.githubusercontent.com/14089426/97789300-2195f780-1be1-11eb-9f28-e18b519a5b4c.png)
Не знаю. стоит ли оно того. Я не совсем понял эту правку - от чего именно нужно избавиться? Самое запутанное задание по этому проекту на моей памяти)
К уже сделанному могу вот еще добавить один пиксель верхнего паддинга к блоку Bluetooth, тогда будет вот так:
![2020-11-01_01-26-50](https://user-images.githubusercontent.com/14089426/97789337-75084580-1be1-11eb-9fc8-4b2ac97c6943.png)
Как лучше?

2020-11-01 13:16 UTC, ILoyso commented on css/style.css
>  }
Зачем ограничение ширины и высоты? Сколько ж можно про высоту и про контент говорить :) Если очень надо - минимальные задаем, но высота тут ни при каких обстоятельствах не нужна
http://joxi.ru/Vm6PnQxCv16v8A

2020-11-01 13:16 UTC, ILoyso commented on css/style.css
> +}
Избавиться нужно от слишком специфичного и тяжело поддержимаемого кода. Мы не должны из-за ПП писать фигню, код всегда должен оставаться понятным и аккуратным
http://joxi.ru/MAj4x1otkEB14m - эти расстояния по макету практически одинаковые (один пиксель это погрешность и забиваем на неё), а значит у нас у каждого филдсета отступ должен быть одинаковый.

Сейчас стало лучше, но можно ещё лучше.
Там где радиобатоны нужно все сделать по аналогии с чекбоксами - список, нижние марджины у элементов списка (всех кроме последнего - вдруг из будет не 2, а 3 или больше).
И тогда вот пример стилей, при которых для последнего филдсета нам тоже не нужно делать отдельный маджин:
http://joxi.ru/bmo48Wztyk1Oq2 - используем тот же марджин, что и везде
http://joxi.ru/Y2LJRXYHEOYxpr
http://joxi.ru/eAOQn7YikQevJm

2020-11-01 13:23 UTC, Ranyar commented on css/style.css
>  }
Без заданной ширины/высоты элемент никак не реагировал должным образом на justify-content

2020-11-01 14:24 UTC, Ranyar commented on catalog.html
> +                </a>
Удалил

2020-11-01 21:08 UTC, Ranyar commented on css/style.css
>  }
Готово!

2020-11-01 22:00 UTC, Ranyar commented on css/style.css
> +}
Сделано!

2020-11-02 07:34 UTC, ILoyso commented on css/style.css
>  }
> Ну и непонятно, зачем нужен width, если его нигде нельзя использовать толком(

Можно в сетке, можно в картинках (если это что-то крупное), можно в декоративных элементах. Как раз ширину много где можно. А вот высоту очень точечно, да, если ты хочешь, чтобы твоя верстка была универсальной и работала хорошо. Так-то можно везде фиксированной высоты наставить, но что толку, если этот сайт развалится от первой же смены контента.

2020-11-02 07:36 UTC, merged