Разметка Главной/index.html
htmlacademy-htmlcss/98669-device-29 pull request #2
Opened 2020-09-11 20:30 UTC by Ranyar

Не совсем понял, в каком именно порядке размечать элементы в хедере и футере, на лекции говорили, что их все равно надо будет совершенно по-разному двигать стилизацией. Старался делать логично.

Также за время разметки Главной и чтения теории возникло несколько вопросов:
1. В [статье](https://htmlacademy.ru/blog/education/all/version-control-system) написано "Каждый коммит хранит полное состояние рабочей области, её папок и файлов проекта."
Значит ли это, что если проект весит 1 Гб, то каждый коммит будет добавлять по гигу? Или все-таки записываются только измененные файлы?
2. Надо ли как-то переписывать .gitattributes в соответствии со [статьей](https://htmlacademy.ru/blog/boost/tools/konec-stroki)?
3. В чем отличие между <a></a> и <a href="#"></a> ? Оба варианта - как бы "заглушки", но первый никуда не ведет, а второй - сам на себя? Не совсем понимаю. Почему-то учили на лекции ставить вообще заглушку "blank.html", а в ТЗ написано делать пустые ссылки href="".
4. Как принято - отбивать отступы пробелами или табами?
5. Пока не понимаю, что делает Fetch в GitHub Desktop, и почему время от времени обновляется автоматически.

2020-09-11 22:02 UTC, ILoyso requested changes
> Не совсем понял, в каком именно порядке размечать элементы в хедере и футере, на лекции говорили, что их все равно надо будет совершенно по-разному двигать стилизацией. Старался делать логично.
Практически всегда лучше размещать элементы в том порядке, в каком мы видим их в макете. Исключений не так много, а подобное решение существенно упростит нам стилизацию. Так что рекомендую изменить порядок

> В статье написано "Каждый коммит хранит полное состояние рабочей области, её папок и файлов проекта." Значит ли это, что если проект весит 1 Гб, то каждый коммит будет добавлять по гигу? Или все-таки записываются только измененные файлы?
В статье используется неоднозначная формулировка. Ты прав, коммит не содержит в себе всю информацию о проекте, то есть по одному коммиту мы не сможем восстановить весь репозиторий. Описание чуть попроще можно прочитать вот здесь https://ru.hexlet.io/courses/git_base/lessons/introduction_to_git_commit/theory_unit

> Надо ли как-то переписывать .gitattributes в соответствии со статьей?
Нет, на данный момент у нас есть все необходимое для текущего проекта. На интенсиве не подразумевается большого количества разных файлов. Если бы проект был разнообразнее - файл нужно было бы дополнить.

> В чем отличие между и ? Оба варианта - как бы "заглушки", но первый никуда не ведет, а второй - сам на себя? Не совсем понимаю. Почему-то учили на лекции ставить вообще заглушку "blank.html", а в ТЗ написано делать пустые ссылки href="".
Повтори вопрос, пожалуйста, гит "съел" описание и я не вижу, какие варианты ты перечислил. Но говоря о заглушках, вариант с "blank.html" странный и я бы не рекомендовала его использовать. Самое классическое и общепринятое - писать символ решетки

> Как принято - отбивать отступы пробелами или табами?
Принято пробелами

> Пока не понимаю, что делает Fetch в GitHub Desktop, и почему время от времени обновляется автоматически.
Что ты имеешь ввиду под "обновляется автоматически"?
А в целом, команда fetch служит для получения данных из удаленного репозитория, но в отличие от pull не делает мердж. Pull = fetch + merge

2020-09-12 06:18 UTC, Ranyar commented on index.html
> +    </header>
Был уверен, что хедер у меня заканчивается после /nav, странно, что у меня там только заголовок. Видимо, после полуночи потерял внимательность(
Исправлю.

2020-09-12 08:39 UTC, Ranyar commented on index.html
> +        <h2>Слайдер</h2>
Изменил.

2020-09-12 08:40 UTC, Ranyar commented on index.html
> +        <div>
Готово.

2020-09-12 08:40 UTC, Ranyar commented on index.html
> +          <span>01</span><!-- Номер слайда, можно стилизовать CSS в большую надпись, как в макете -->
Сделал.

2020-09-12 08:40 UTC, Ranyar commented on index.html
> +          </ul>
Спасибо, заменил теги на button.

2020-09-12 08:40 UTC, Ranyar commented on index.html
> +        а "фоновая иконка", и можно оформить как CSS background-image у заголовка. Как лучше? Каждый отдельный блок будет кликабелен -->
Тогда коммент пока в коде оставлю, чтобы не забыть?

2020-09-12 08:40 UTC, Ranyar commented on index.html
> +          </li>
По поводу ссылки - здесь меня немного запутала формулировка в ТЗ, но теперь я понял)
По заголовкам - код прошёл валидацию в w3c, поэтому я не обратил внимания сразу. Теперь проверил в сервисе https://caninclude.glitch.me/ и вижу, что решение сомнительное. Спасибо за замечание, Ирина!
Заменил заголовки на текст в ссылках.

2020-09-12 08:40 UTC, Ranyar commented on index.html
> +        сделал списком без ссылок -->
Здесь мой прошлый опыт работы ПМ'ом в веб-студиях сыграл со мной злую шутку( видел оба варианта реализации, поэтому понадеялся целиком на ТЗ.
Ты очень верно указала на стайлгайд и состояния в нем - это должно было сразу натолкнуть меня на мысль о ссылках, но не обратил внимания(
Спасибо. Добавил ссылки.

2020-09-12 08:40 UTC, Ranyar commented on index.html
> +          <p>Самая длинная палка для селфи доступна в нашем магазине.<br>
Убрал <br>

2020-09-12 08:40 UTC, Ranyar commented on index.html
> +      <a href="tel:+74954959595">Тел.: +7 (495) 495-95-95</a>
Поправил)

2020-09-12 08:56 UTC, Ranyar commented on index.html
> +      <ul>
Перенес закрывающий /header куда нужно, на что ночью не обратил внимания, был уверен, что там вся навигация)
По поводу порядка элементов - по порядку должен бы идти сначала логотип, потом поиск, затем Войти, Сравнить, Корзина, и после этого уже навигационное горизонтальное меню Каталог, Доставка, Гарантия, Контакты.
Но так как логотип тоже является частью навигации, то логично было включить его тоже в тег nav.

2020-09-12 17:53 UTC, ILoyso commented on index.html
> +      <ul>
Логотипы не критично находиться в навигации, особенно если из-за этого усложняется его позиционировние. Пока можно оставить как есть, ты поймешь, о чем я говорю, когда будет лекция по сеткам

2020-09-12 17:54 UTC, ILoyso commented on index.html
> +        а "фоновая иконка", и можно оформить как CSS background-image у заголовка. Как лучше? Каждый отдельный блок будет кликабелен -->
Да, пусть будет

2020-09-12 17:56 UTC, ILoyso approved these changes

2020-09-12 17:56 UTC, ILoyso commented on index.html
> +          </li>
Не все ссылки будут вести на страницу каталога. У нас, в данном случае, мы верстаем только одну, и там говорится о моноподах для селфи, поэтому только эта ссылка по ТЗ должна вести на каталог, в остальных можно оставить заглушки. Можешь поправить это вместе со следующим заданием

2020-09-12 17:57 UTC, merged