Разметил страницу каталога
htmlacademy-htmlcss/98669-device-29 pull request #3
Opened 2020-09-13 19:15 UTC by Ranyar

2020-09-13 19:48 UTC, ILoyso requested changes

2020-09-13 19:48 UTC, ILoyso commented on catalog.html
> +        <!-- Здесь будет фильтр -->
Сортировка это не форма, поэтому ссылки в ней нужно разметить уже сейчас

2020-09-13 19:48 UTC, ILoyso commented on catalog.html
> +            </a>
Лучше абзац, а в нем ссылка, чтобы строчный элемент лежал внутри блочного

2020-09-13 19:48 UTC, ILoyso commented on catalog.html
> +            <button type="button">Добавить к сравнению</button>
Опять таки, вам потом расскажут почему, но здесь должны быть ссылки :)

2020-09-13 19:48 UTC, ILoyso commented on catalog.html
> +        <a>
Ссылка на главную страницу

2020-09-13 20:37 UTC, Ranyar commented on catalog.html
> +        <a>
Сделал логотип ссылкой на главную.

2020-09-13 20:40 UTC, Ranyar commented on catalog.html
> +            <button type="button">Добавить к сравнению</button>
Говорили (и в интерактивах было), что ссылки ведут на другие страницы, а кнопки - что-либо активируют, и так легко понять, что перед тобой - кнопка или ссылка, и что зачастую трудно разобраться)

2020-09-13 20:46 UTC, Ranyar commented on catalog.html
> +            </a>
Поправил)

2020-09-13 20:47 UTC, Ranyar commented on catalog.html
> +        <!-- Здесь будет фильтр -->
Так и подмывало сделать кнопками, но решил списком со ссылками.

2020-09-14 07:03 UTC, ILoyso commented on catalog.html
> +        </ul>
Активные пункты сортировки, как и в других местах, делаем без href
http://joxi.ru/Drlgv1jh0p469A

2020-09-14 07:03 UTC, ILoyso commented on catalog.html
> +            <button type="button">Добавить к сравнению</button>
Да, это верно. Но есть ещё второй момент - кнопки работают только тогда, когда на сайте работает JS. Если же по каким-то причинам он отвалился, то мы не имеем права терять критично важную функциональность - поиск, покупка и тд. Поэтому подобные элементы делаются именно ссылками и если JS не работает, то вместо мгновенного действия происходит либо перезагрузка страницы (с запросом на сервер), либо переход на другую страницу (аналогично, с запросом, например, на добавление в корзину).
Соответственно, кнопками в итоге остаются только некритичные вещи, вроде переключений слайдера и прочих мелочей, а все остальное, что является важным и должно работать в любых условиях - ссылки

2020-09-14 08:28 UTC, Ranyar commented on catalog.html
> +        </ul>
Доработал.

2020-09-14 08:45 UTC, ILoyso approved these changes

2020-09-14 08:45 UTC, merged