Базовая стилизация главной страницы
htmlacademy-htmlcss/98669-device-29 pull request #4
Opened 2020-09-20 19:48 UTC by Ranyar

2020-09-21 08:38 UTC, ILoyso requested changes

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +  --basic-grey: #464646;
Можно без basic в названии, будет только проще

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
- путь до шрифта задан верно, все ок
- явно прописывать font-weight и font-style нужно для каждого шрифта, да
- если здесь font-family в кавычках, то везде в кавычках (критерий единообразия)

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Неверно заданы пути, шрифты не подключаются

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +  font-size: 15px;
line-height здесь тоже имеет смысл сразу задать, так же как и базовый (контентный) цвет текста

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Если ты уже сейчас хочешь добавить сеточный контейнер-центровщик, то для этого лучше использовать отдельный класс. То есть создаем класс container, в нем задаем ширину, левый и правый марджины (верхний и нижний не трогаем) и потом в разметке добавляем этот класс там. где нам нужно. Тогда стили, отвечающие за ширину, будут в одном месте и поддерживать код будет проще

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +  font-style: normal;
Нет смысла задавать font-style: normal каждый раз, так как это свойство наследуется от родителя. Мы один раз задали его для боди и этого достаточно
Актуально везде, где встречается

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Мы уже задали для боди базовые характеристики текста и они наследуются у нас везде. Соответственно, если стили совпадают со стилями боди, их не нужно задавать повторно. Убираем все, что повторяется

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Половина этих стилей дублирует друг друга (и частично стили боди). Решением лучше будет:
- задать класс для dl и к этому классу прописать все нужные стили для dt
- для dl переопределить те стили, которые отличаются - размер шрифта, высота строки

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Критерий единообразия: отступ везде 2 пробела, значит и здесь тоже

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Критерий единообразия: в разных местах кода разные отступы при описании градиента в фоне, нужно сделтаь везде одинаково.

Плюс для наведения можно просто написать `background: var(--special-yellow-dark);` и результат будет тот же

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +  font-family: Gilroy;
Нет альтернативного шрифта, добавляем везде, где нужно. Актуально здесь и ниже

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +.popular-list-item a{
Здесь и ниже должны быть пробелы перед фигурными скобками

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
http://joxi.ru/Vm6Z6nVCjgRKlm
В данном случае это не только состояние при нажатии, но и активная кнопка, то есть выделенный активный слайд. Соответственно нужно добавить класс .active и стилизовать его (помним, что активная кнопка не должна реагировать на наведение и нажатие)

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Такое же поведение описано для button-link, соответственно сейчас мы просто дублируем код. Давай стандартное наведение и нажатие у кнопок вынесем в класс .button, а переопределять будем уже по дополнительным классам и только там, где оно отличается. Стандартные паддинги так же должны быть в .button заданы и их тоже переопределяем только там, где нужно (и не для ховер и актив, а для дефолтного вида)
То есть, например, здесь, у нас ховер не должен отличаться, а вот актив - должен, соответственно описать нужно только его

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Через псевдоэлементы будем делать, пока можно убрать это, так как подход будет другой

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
1. Не нужно каскадом переопределять стили кнопок. Как я написала выше, стандартные паддинги и поведение ховера мы выносим в класс .button
2. Если здесь отличаются паддинги, мы добавляем класс .button-about и для него задаем только паддинги (потому что только они у нас и отличаются)

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
- border: none - общий стить, должен быть задан у дефолтного класса .button
- box-sizing: border-box - аналогично, выносим в дефолтную кнопку
- width: 260px - ограничивать ширину кнопок это плохая практика, потому что верстальщик всегда должен учитывать, что текст может измениться и он может не поместиться. меняем на min-width
- height: 40px - аналогично, плохая практика. Плюс мы везде задавали высоту паддингами, значит и здесь делаем так же

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Дублирование стилей из боди

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +.navigation-list  a {
Критерий единообразия: лишний пробел перед "а", аналогично ниже

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> +}
Частично дублируем стили из боди

2020-09-21 08:38 UTC, ILoyso commented on css/style.css
> + .modal-button:focus {
Кстати, это странно, делать состояние фокус и актив одинаковое визуально. Как правило фокус чаще объединяют с ховером

2020-09-21 08:38 UTC, ILoyso commented on index.html
> +    <section class="modal modal-write_us">
Нижние подчеркивания в именах классов допустимы, но нигде больше ты их не используешь, поэтому здесь нарушается единообразие

2020-09-22 17:11 UTC, Ranyar commented on css/style.css
> +  --basic-grey: #464646;
Поправил.

2020-09-22 17:24 UTC, Ranyar commented on css/style.css
> +}
Поправил.

2020-09-22 19:31 UTC, Ranyar commented on css/style.css
> +}
Сделал.

2020-09-23 16:18 UTC, Ranyar commented on css/style.css
> +}
Поправил, наверное, случайно нажал и не заметил

2020-09-23 16:48 UTC, Ranyar commented on css/style.css
> +}
Готово.

2020-09-23 16:55 UTC, Ranyar commented on css/style.css
> +  font-family: Gilroy;
Добавил

2020-09-23 16:57 UTC, Ranyar commented on css/style.css
> +.popular-list-item a{
Исправил.

2020-09-23 17:00 UTC, Ranyar commented on css/style.css
> +}
Понял, пока скрыл в комментарий

2020-09-23 17:05 UTC, Ranyar commented on css/style.css
> +.navigation-list  a {
Поправил.

2020-09-23 17:07 UTC, Ranyar commented on index.html
> +    <section class="modal modal-write_us">
Переделал)

2020-09-23 17:09 UTC, Ranyar commented on css/style.css
> +  font-style: normal;
Убрал везде, кроме body и @font-face

2020-09-23 19:15 UTC, Ranyar commented on css/style.css
> + .modal-button:focus {
Поправил, а заодно прочитал пару статей об этих состояниях

2020-09-23 19:19 UTC, Ranyar commented on css/style.css
> +}
Пока убрал в комменты, сделаю сразу гридами в следующей домашке

2020-09-23 19:26 UTC, Ranyar commented on css/style.css
> +}
Изменил.

2020-09-23 19:29 UTC, Ranyar commented on css/style.css
> +}
Поправил. Теперь действительно удобнее стало)

2020-09-23 19:31 UTC, Ranyar commented on css/style.css
> +  font-size: 15px;
Задал line-height: 28px; в body

2020-09-23 19:36 UTC, Ranyar commented on css/style.css
> +}
Готово!

2020-09-24 11:00 UTC, Ranyar commented on css/style.css
> +}
Сделал, теперь этот фрагмент кода стал гораздо короче)

2020-09-24 12:43 UTC, Ranyar commented on css/style.css
> +}
Done.

2020-09-24 12:43 UTC, Ranyar commented on css/style.css
> +}
Вынес в .button, поправил

2020-09-24 12:45 UTC, Ranyar commented on css/style.css
> +}
Сделано

2020-09-24 12:46 UTC, Ranyar commented on css/style.css
> +}
Все общие свойства перенес в .button, в отдельных кнопках переопределял только паддинги

2020-09-24 13:30 UTC, ILoyso approved these changes

2020-09-24 13:30 UTC, ILoyso commented on css/style.css
> +  font-family: Open Sans, Arial, sans-serif;
Единообразно нужно
http://joxi.ru/ZrJzQZvTMV4k4r

2020-09-24 13:30 UTC, ILoyso commented on css/style.css
> +}
В active тоже можно просто `background: var(--yellow-dark);` оставить

2020-09-24 13:30 UTC, ILoyso commented on css/style.css
> +}
Переделаем это на этапе декоративных элементов, пока пусть будет

Нужно добавить активный класс. У нас это слайдер, соответственно каждая кнопка может быть активна (выбрана) и тогда она должна быть изначально черной и никак не реагировать на наведение и нажатие. Нужно в разметке добавить для первой кнопки класс (например .active) и для него задать всё это

2020-09-24 13:30 UTC, merged