Стилизация страницы каталога
htmlacademy-htmlcss/98669-device-29 pull request #5
Opened 2020-09-25 20:02 UTC by Ranyar

2020-09-26 20:40 UTC, ILoyso requested changes

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +}
Зачем нам здесь задавать цвет текста?

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +}
http://joxi.ru/v296kWPipj6QdA
Третья ссылка активная - мы находимся на этой странице, а значит она не должна реагировать на наведение и нажатие

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +}
http://joxi.ru/gmv45qvt10XBLA
Аналогично, активная ссылка, не должна реагировать на наведение и нажатие

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +}
В других местах, где используешь класс heading, с ним идет второй класс, к которому дописываем остальные свойства. Давай здесь по аналогии сделаем

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +  font-family: Gilroy;
Нет альтернативного шрифта

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +}
По критериям все цвета должны быть вынесены в переменные, поэтому здесь тоже нужно вынести и использовать переменную

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +}
Лучше задать цифрам дополнительный класс и дописать эти стили к нему, такое решение будет универсальнее, чем каскад
Плюс http://joxi.ru/Q2KNapYtvgjXRm первая страница активная, а значит должна быть черного цвета и не реагировать на наведение и нажатие

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +.pagination-button {
У кнопки "Назад" при нажатии цвет текста не меняется (а должен становиться серым)

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +}
Обсуждали в прошлом ПР, что фокус принято объединять с ховером, а не с active стейтом

2020-09-26 20:40 UTC, ILoyso commented on css/style.css
> +.pagination-list .pagination-button:focus {
Фокус лучше объединять с ховером

2020-09-27 10:51 UTC, Ranyar commented on css/style.css
> +}
Убрал

2020-09-27 10:52 UTC, Ranyar commented on css/style.css
> +  font-family: Gilroy;
Добавил

2020-09-27 11:15 UTC, Ranyar commented on css/style.css
> +}
Сделал

2020-09-27 11:18 UTC, Ranyar commented on css/style.css
> +}
Вынес в кастомное свойство сразу полупрозрачный цвет. Раньше не думал, что сработает.

2020-09-27 11:44 UTC, Ranyar commented on css/style.css
> +}
Поправил

2020-09-27 11:44 UTC, Ranyar commented on css/style.css
> +.pagination-list .pagination-button:focus {
Поправил

2020-09-27 13:54 UTC, Ranyar commented on css/style.css
> +}
Поправил

2020-09-27 13:54 UTC, Ranyar commented on css/style.css
> +}
Поправил

2020-09-27 13:54 UTC, Ranyar commented on css/style.css
> +.pagination-button {
Поправил

2020-09-27 13:54 UTC, Ranyar commented on css/style.css
> +}
Поправил

2020-09-27 14:10 UTC, ILoyso approved these changes

2020-09-27 14:10 UTC, merged