Сетка главной на гридах
htmlacademy-htmlcss/98669-device-29 pull request #7
Opened 2020-10-06 12:51 UTC by Ranyar

2020-10-06 18:47 UTC, ILoyso requested changes

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
Не нужно фиксировать высоту секций, хедера и футера, если нет критичной необходимости. Она всегда должна быть по высоте контента, чтобы при переполнении ничего не ломалось.

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +  margin-left: 60px;
http://joxi.ru/52ag5LVhb8y9gr - это паддинги хедера

В сети много статей на тему того, когда использовать паддинги, а когда марджины, поищи и почитай. Причем рекомендую сразу читать несколько разных, потому что подходов очень много.

Из основного, что я бы рекомендовала помнить и стараться использовать при разработке:

- Марджины - внешние отступы, мы их используем чтобы оттолкнуть блоки друг от друга. Пример: несколько абзацев, которые идут друг за другом; карточки в каталоге; отступ между заголовком и текстом и тд
- Паддинги - внутренние отступы, мы их используем чтобы оттолкнуть контент от какого-то его родителя. Пример: при разработке кнопки мы используем именно внутренние отступы; отступы от границ секции до её контента; увеличение ссылки за счет паддингов с целью увеличения области клика; выделение места под псевдоэлементы или какой-то декор и тд
- При работе с так называемым вертикальным ритмом страницы лучше всегда придерживаться одного подхода. Например всегда использовать только верхние марджины (или только нижние). Плюсов много: единообразное и предсказуемое поведение, проще управлять отступами, проще добавлять новые блоки

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
По макету у первой ссылки должно быть больше пространства, чем у двух других, а сейчас задано одинаковое для всех

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
У первого пункта навигации ("Каталог") должно быть больше места, чем у других, данный темплейт колонок нам не подходит

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
1. Огромные марджины, компенсирующие сетку - плохо. Это нужно решать именно на уровне сетки
2. Из описания паддингов выше - это отступы, отталкивающие контент внутри себя, следовательно - паддинги
3. Лучше не завязываться на порядковый номер, и если нужно задать уникальные стили, то добавлять класс

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
У нас одна строка, зачем здесь grid-row

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
Зачем это?
У родителя этих элементов не задан грид, тем более они просто идут друга за другом в верстке и нас это устраивает

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
Здесь избыточен грид. Это микросетка и флекс здесь уместнее, нам всего лишь нужны три кнопки друг за другом с небольшими отступами

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
Избыточный грид, избыточный впаррер в целом

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
- обсуждали высоту кнопок и переполнение уже раньше
- стили от грида не нужны (так как сам грид выше не нужен)

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
А надо ли?

2020-10-06 18:47 UTC, ILoyso commented on css/style.css
> +}
http://joxi.ru/RmzE9L3CRpbM5r

2020-10-08 16:22 UTC, Ranyar commented on css/style.css
> +}
Флексы пока не изучил, поэтому пока закомментировал это правило.

2020-10-08 16:24 UTC, Ranyar commented on css/style.css
> +}
Убрал, три кнопки встали под кнопку "Подробнее". Они ведь потом уйдут куда надо при позиционировании, и отступа снизу не будет?

2020-10-08 16:27 UTC, Ranyar commented on css/style.css
> +}
Убрал.

2020-10-08 16:31 UTC, Ranyar commented on css/style.css
> +}
Убрал.

2020-10-08 16:33 UTC, Ranyar commented on css/style.css
> +}
Убрал, и ничего не сломалось! Я в шоке, думал что все на этом и держится)

2020-10-08 16:52 UTC, Ranyar commented on css/style.css
> +}
Поправил здесь и в footer-links, общий верхний отступ вынес в паддинг футера

2020-10-08 17:15 UTC, Ranyar commented on index.html
> +              </div>
Готово!

2020-10-08 17:24 UTC, Ranyar commented on css/style.css
> +}
Убрал)

2020-10-09 09:55 UTC, Ranyar commented on css/style.css
> +}
Поправил везде

2020-10-09 10:06 UTC, Ranyar commented on index.html
>            </a>
Исправил. Ввела в заблуждение фраза в ТЗ про "картинки товаров должны быть кликабельны" или что-то вроде того

2020-10-09 10:08 UTC, Ranyar commented on index.html
> +            </div>
Убрал общий див-обертку

2020-10-09 10:51 UTC, Ranyar commented on css/style.css
> +}
Убрал фиксацию высоты

2020-10-09 11:34 UTC, Ranyar commented on css/style.css
> +}
Убрал.

2020-10-09 11:42 UTC, Ranyar commented on css/style.css
> +}
Сделал другой темплейт, теперь у первого пункта 48%

2020-10-09 11:45 UTC, Ranyar commented on css/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
Сделал

2020-10-09 11:53 UTC, Ranyar commented on css/style.css
> +  margin-left: 60px;
Спасибо, сделал паддингами слева и справа)

2020-10-09 12:37 UTC, ILoyso commented on css/style.css
>  .slider a {
Теперь эти стили вообще относятся к кнопке, которая внутри правой части. Если мы хотим задать колонки для картинки - делаем для неё обертку, задаем класс и по нему стилизуем. А в целом - у нас две колонки по 1fr и два чайлда - они и так сами встанут как нам нужно, так что можно просто здесь удалить весь селектор и все

2020-10-09 12:37 UTC, ILoyso commented on css/style.css
> +}
Тут уж не знаю, в каком порядке и как ты это делал. Если задавал родителю грид - могло что-то меняться, но в любом случае грид здесь не нужен

2020-10-09 12:38 UTC, ILoyso commented on css/style.css
> +}
Мы их вообще вынесем из первого слайда (они должны быть вне слайдов) и потом подвинем с помощью позиционирования куда нужно, да

2020-10-09 12:39 UTC, ILoyso approved these changes

2020-10-09 12:40 UTC, merged